#!/usr/bin/env bash
# Capture live testnet evidence for the W2/W3 modules on the reference compliant
# token: runs a sequence of pass/revert operations, records the on-chain tx hashes
# of the submitted (passing + rule-arming) transactions, and writes a reviewer-
# friendly report to docs/evidence-testnet.md.
#
# Pass/revert reverts fail at simulation (a compliance pre-check panics before the
# tx is submitted), so a denied operation has no on-chain hash — its evidence is the
# rule-arming tx (real hash) plus the on-chain read that proves the rule is active.
#
# Usage: bash scripts/capture-evidence.sh   (after scripts/deploy-testnet.sh)
set -euo pipefail

NET=testnet
J=scripts/deployed.testnet.json
val() { python3 -c "import json,sys;print(json.load(open('$J'))$1)"; }

REF_TOKEN=$(val "['referenceToken']['token']")
DENYLIST=$(val "['referenceToken']['denylist']")
INVESTORS=$(val "['referenceToken']['maxInvestorsPerCountry']")
WINDOW=$(val "['referenceToken']['transferWindow']")
ALICE=$(val "['accounts']['alice']")
BOB=$(val "['accounts']['bob']")
FRANK=$(val "['accounts']['frank']")

inv()  { stellar contract invoke --id "$1" --source "$2" --network "$NET" -- "${@:3}" 2>/dev/null | tail -1; }
# invoke returning the submitted tx hash (or empty on failure)
invh() { stellar contract invoke --id "$1" --source "$2" --network "$NET" -- "${@:3}" 2>&1 | grep -oE 'tx/[0-9a-f]{64}' | head -1 | cut -d/ -f2; }
xlt()  { echo "[\`${1:0:12}…\`](https://stellar.expert/explorer/testnet/tx/$1)"; }

echo "▸ PASS: mint 10 to alice (already a US holder → allowed)…"
H_MINT=$(invh "$REF_TOKEN" deployer mint --to "$ALICE" --amount 10)
echo "  tx=$H_MINT"

echo "▸ PASS: transfer alice→bob 5 (bob is a new DE holder, under cap → allowed)…"
H_XFER=$(invh "$REF_TOKEN" alice transfer --from "$ALICE" --to "$BOB" --amount 5)
echo "  tx=$H_XFER"

echo "▸ REVERT: mint to frank (2nd US holder, cap 1)…"
if inv "$REF_TOKEN" deployer mint --to "$FRANK" --amount 1 >/dev/null 2>&1; then R_INV="❌ unexpectedly passed"; else R_INV="✅ reverted"; fi
US_COUNT=$(inv "$INVESTORS" deployer count --country 840)
echo "  $R_INV (US count=$US_COUNT)"

echo "▸ REVERT: denylist bob, then transfer alice→bob…"
H_DENY=$(invh "$DENYLIST" deployer add_to_denylist --account "$BOB")
IS_DENIED=$(inv "$DENYLIST" deployer is_denied --account "$BOB")
if inv "$REF_TOKEN" alice transfer --from "$ALICE" --to "$BOB" --amount 1 >/dev/null 2>&1; then R_DENY="❌ unexpectedly passed"; else R_DENY="✅ reverted"; fi
H_UNDENY=$(invh "$DENYLIST" deployer remove_from_denylist --account "$BOB")
echo "  arm tx=$H_DENY  is_denied=$IS_DENIED  $R_DENY"

echo "▸ REVERT: pause the window, then mint to alice…"
H_PAUSE=$(invh "$WINDOW" deployer pause)
IS_PAUSED=$(inv "$WINDOW" deployer is_paused)
if inv "$REF_TOKEN" deployer mint --to "$ALICE" --amount 1 >/dev/null 2>&1; then R_PAUSE="❌ unexpectedly passed"; else R_PAUSE="✅ reverted"; fi
H_UNPAUSE=$(invh "$WINDOW" deployer unpause)
echo "  pause tx=$H_PAUSE  is_paused=$IS_PAUSED  $R_PAUSE"

echo "▸ Writing docs/evidence-testnet.md…"
cat > docs/evidence-testnet.md <<MD
# Live testnet evidence — W2/W3 modules (Instaward #1, D2)

Generated by [\`scripts/capture-evidence.sh\`](../scripts/capture-evidence.sh) against the reference compliant token deployed by [\`scripts/deploy-testnet.sh\`](../scripts/deploy-testnet.sh). Every hash below is a real, explorable **testnet** transaction.

> A **denied** operation reverts during simulation (a compliance pre-check panics before the transaction is submitted), so it has **no on-chain hash**. Its evidence is the rule-arming transaction (a real hash) plus an on-chain read proving the rule is active.

## Contracts (reference token)

| Contract | Address |
|---|---|
| reference token | [\`$REF_TOKEN\`](https://stellar.expert/explorer/testnet/contract/$REF_TOKEN) |
| module-denylist | [\`$DENYLIST\`](https://stellar.expert/explorer/testnet/contract/$DENYLIST) |
| module-max-investors-per-country | [\`$INVESTORS\`](https://stellar.expert/explorer/testnet/contract/$INVESTORS) |
| module-transfer-window | [\`$WINDOW\`](https://stellar.expert/explorer/testnet/contract/$WINDOW) |

## Passing transactions (submitted on-chain)

| Operation | Result | Transaction |
|---|---|---|
| \`mint(alice, 10)\` — existing US holder | ✅ passed | $(xlt "$H_MINT") |
| \`transfer(alice→bob, 5)\` — new DE holder under cap | ✅ passed | $(xlt "$H_XFER") |

## Rule enforcement (denials)

| Module | Arming transaction | On-chain proof | Denied operation |
|---|---|---|---|
| **MaxInvestorsPerCountry** | _(cap set at deploy)_ | \`count(840) = $US_COUNT\` (US at cap 1) | \`mint(frank, 1)\` — 2nd US holder → $R_INV |
| **Denylist** | $(xlt "$H_DENY") \`add_to_denylist(bob)\` | \`is_denied(bob) = $IS_DENIED\` | \`transfer(alice→bob, 1)\` → $R_DENY · restored: $(xlt "$H_UNDENY") |
| **TransferWindow** | $(xlt "$H_PAUSE") \`pause()\` | \`is_paused = $IS_PAUSED\` | \`mint(alice, 1)\` while frozen → $R_PAUSE · resumed: $(xlt "$H_UNPAUSE") |

_Re-run \`bash scripts/capture-evidence.sh\` to regenerate this report against the current deployment._
MD
echo "✅ Done. Wrote docs/evidence-testnet.md"